controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    FL_hip_controller:
      type: unitree_legged_control/UnitreeJointController

    # FL_thigh_controller:
    #   type: unitree_legged_control/UnitreeJointController

FL_hip_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
    # pid: {p: 100.0, i: 0.0, d: 5.0}

    command_interfaces:
      - position

    state_interfaces:
      - position
